#ifndef CONNECTION_CONFIG_H
#define CONNECTION_CONFIG_H

//#define NON_BLOCKING_TCP_CONNECTION
//#define NON_BLOCKING_UDP_CONNECTION
//#define BLOCKING_TCP_CONNECTION
#define BLOCKING_UDP_CONNECTION

#if defined(BLOCKING_UDP_CONNECTION) || defined(BLOCKING_TCP_CONNECTION)
#define BLOCKING_MODE
#endif

#if defined(BLOCKING_UDP_CONNECTION) || defined(NON_BLOCKING_UDP_CONNECTION)
#define UDP_MODE
#else
#define TCP_MODE
#endif

#endif
